package com.civka.monopoly.api.dto;

public enum ProjectType {
    BREAD_AND_CIRCUSES,
    CAMPUS_RESEARCH_GRANTS,
    COMMERCIAL_HUB_INVESTMENT,
    ENCAMPMENT_TRAINING,
    HARBOR_SHIPPING,
    INDUSTRIAL_ZONE_LOGISTICS,
    THEATER_SQUARE_PERFORMANCES,
    LAUNCH_EARTH_SATELLITE,
    LAUNCH_MOON_LANDING,
    LAUNCH_MARS_COLONY,
    EXOPLANET_EXPEDITION,
    TERRESTRIAL_LASER_STATION,
}
